language: java
jdk:
  - oraclejdk7

before_install:
  # Update to Gradle 1.7
  - wget http://services.gradle.org/distributions/gradle-1.7-bin.zip
  - unzip gradle-1.7-bin.zip
  - export GRADLE_HOME=$PWD/gradle-1.7
  - export PATH=$GRADLE_HOME/bin:$PATH

script:
  - gradle clean test -q
